version: "3"
services:
  # Auto activates my trap card
  entry_service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ColorMEF-dev
    ipc: host
    user: "colormef"
    volumes:
      - ${PWD}/:/workspaces/ColorMEF
    deploy:
      # GPU support
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: [ "0" ]
              capabilities: [ gpu ]

  train_service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ColorMEF-train
    ipc: host
    user: "colormef"
    entrypoint: [ "/bin/bash" ]
    command: train.sh
    volumes:
      - ${PWD}/:/workspaces/ColorMEF
    deploy:
      # GPU support
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: [ "0" ]
              capabilities: [ gpu ]
